name: CI
on: [push]

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest] 
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8.10
      - name: Python Poetry Action
        uses: abatilo/actions-poetry@v2.1.3
        with:
          poetry-version: 1.1.13
      - name: Prepare Poetry environment
        run: poetry install
      - name: Run black
        run: poetry run black --diff .
      - name: Run flake8
        run: poetry run flake8 .
      # - name: Run mypy
      #   run: poetry run mypy .
      - name: Run pytest
        run: poetry run pytest .